<?php

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $record_key
 * @property boolean $show_list
 * @property Doctrine_Collection $Pictures
 * @property Doctrine_Collection $Article
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getRecordKey()  Returns the current record's "record_key" value
 * @method boolean             getShowList()   Returns the current record's "show_list" value
 * @method Doctrine_Collection getPictures()   Returns the current record's "Pictures" collection
 * @method Doctrine_Collection getArticle()    Returns the current record's "Article" collection
 * @method Gallery             setName()       Sets the current record's "name" value
 * @method Gallery             setRecordKey()  Sets the current record's "record_key" value
 * @method Gallery             setShowList()   Sets the current record's "show_list" value
 * @method Gallery             setPictures()   Sets the current record's "Pictures" collection
 * @method Gallery             setArticle()    Sets the current record's "Article" collection
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qui_galleries');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Nazwa galerii',
             'length' => 255,
             ));
        $this->hasColumn('record_key', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('show_list', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Picture as Pictures', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $this->hasMany('Article', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'qui_galleries_translation',
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             'indexName' => 'gallery_slug',
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}