<?php

/**
 * BaseActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $type_id
 * @property clob $description
 * @property time $time_from
 * @property time $time_to
 * @property integer $day
 * @property ActivityType $ActivityType
 * 
 * @method string       getName()         Returns the current record's "name" value
 * @method integer      getTypeId()       Returns the current record's "type_id" value
 * @method clob         getDescription()  Returns the current record's "description" value
 * @method time         getTimeFrom()     Returns the current record's "time_from" value
 * @method time         getTimeTo()       Returns the current record's "time_to" value
 * @method integer      getDay()          Returns the current record's "day" value
 * @method ActivityType getActivityType() Returns the current record's "ActivityType" value
 * @method Activity     setName()         Sets the current record's "name" value
 * @method Activity     setTypeId()       Sets the current record's "type_id" value
 * @method Activity     setDescription()  Sets the current record's "description" value
 * @method Activity     setTimeFrom()     Sets the current record's "time_from" value
 * @method Activity     setTimeTo()       Sets the current record's "time_to" value
 * @method Activity     setDay()          Sets the current record's "day" value
 * @method Activity     setActivityType() Sets the current record's "ActivityType" value
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qui_activities');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => true,
             'length' => 65532,
             ));
        $this->hasColumn('time_from', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('time_to', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('day', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ActivityType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}