<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property clob $address
 * @property clob $map
 * 
 * @method string  getEmail()   Returns the current record's "email" value
 * @method clob    getAddress() Returns the current record's "address" value
 * @method clob    getMap()     Returns the current record's "map" value
 * @method Contact setEmail()   Sets the current record's "email" value
 * @method Contact setAddress() Sets the current record's "address" value
 * @method Contact setMap()     Sets the current record's "map" value
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qui_contact');
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Nazwa/Tytuł',
             'length' => 255,
             ));
        $this->hasColumn('address', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => false,
             'default' => '<p></p>',
             'length' => 65532,
             ));
        $this->hasColumn('map', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => false,
             'default' => '',
             'length' => 65532,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'qui_contact_translation',
             'fields' => 
             array(
              0 => 'email',
              1 => 'address',
              2 => 'map',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}