<?php

/**
 * BasePicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gallery_id
 * @property string $file
 * @property string $title
 * @property boolean $is_default
 * @property Gallery $Gallery
 * 
 * @method integer getGalleryId()  Returns the current record's "gallery_id" value
 * @method string  getFile()       Returns the current record's "file" value
 * @method string  getTitle()      Returns the current record's "title" value
 * @method boolean getIsDefault()  Returns the current record's "is_default" value
 * @method Gallery getGallery()    Returns the current record's "Gallery" value
 * @method Picture setGalleryId()  Sets the current record's "gallery_id" value
 * @method Picture setFile()       Sets the current record's "file" value
 * @method Picture setTitle()      Sets the current record's "title" value
 * @method Picture setIsDefault()  Sets the current record's "is_default" value
 * @method Picture setGallery()    Sets the current record's "Gallery" value
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePicture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qui_pictures');
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_default', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'qui_pictures_translation',
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}