<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $file
 * @property string $record_key
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $ArticleFile
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getFile()        Returns the current record's "file" value
 * @method string              getRecordKey()   Returns the current record's "record_key" value
 * @method Doctrine_Collection getArticles()    Returns the current record's "Articles" collection
 * @method Doctrine_Collection getArticleFile() Returns the current record's "ArticleFile" collection
 * @method File                setName()        Sets the current record's "name" value
 * @method File                setFile()        Sets the current record's "file" value
 * @method File                setRecordKey()   Sets the current record's "record_key" value
 * @method File                setArticles()    Sets the current record's "Articles" collection
 * @method File                setArticleFile() Sets the current record's "ArticleFile" collection
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qui_files');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Nazwa pliku',
             'length' => 255,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('record_key', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', array(
             'refClass' => 'ArticleFile',
             'local' => 'file_id',
             'foreign' => 'article_id'));

        $this->hasMany('ArticleFile', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'qui_files_translation',
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             'indexName' => 'file_slug',
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}