<?php

/**
 * BaseArticleFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $file_id
 * @property Article $Article
 * @property File $File
 * 
 * @method integer     getArticleId()  Returns the current record's "article_id" value
 * @method integer     getFileId()     Returns the current record's "file_id" value
 * @method Article     getArticle()    Returns the current record's "Article" value
 * @method File        getFile()       Returns the current record's "File" value
 * @method ArticleFile setArticleId()  Sets the current record's "article_id" value
 * @method ArticleFile setFileId()     Sets the current record's "file_id" value
 * @method ArticleFile setArticle()    Sets the current record's "Article" value
 * @method ArticleFile setFile()       Sets the current record's "File" value
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qui_articles_files');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('connection', 'globocam_classic');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}