<?php

/**
 * ActivityTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityType');
    }

    public function getBySlugs($slugs = array())
    {
        $q = Doctrine_Query::create()
                ->from('ActivityType a')
                ->whereIn('a.slug', $slugs);

        return $q->execute();

    }
}