<?php

/**
 * ActivityType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ActivityType extends BaseActivityType
{
    public function getActivitiesArray()
    {
    	$q = Doctrine_Query::create()
    		->from('Activity a')
    		->where('a.type_id =?', $this->getPrimaryKey())
    		->orderBy('a.time_from');

    	$tmps = $q->execute();

    	$return = array();

    	foreach($tmps as $tmp)
    	{
    		$time_from = date('H:i', strToTime($tmp->getTimeFrom()));
    		$time_to   = date('H:i', strToTime($tmp->getTimeTo()));
    		$return[$time_from.' - '.$time_to][$tmp->getDay()] = $tmp;
    	}

    	return $return;
    }
}
