<?php

/**
 * ArtcategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtcategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtcategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Artcategory');
    }

    public function getArtcategoriesQuerybackend(Doctrine_Query $q)
    {
    	$rootAlias = $q->getRootAlias();
	    $q->leftJoin($rootAlias . '.Translation t');
	    return $q;
    }

    public function getArtcategoriesQuery()
    {
    	$q = Doctrine_Query::create()
    		->from('Artcategory a')
	   		->leftJoin('a.Translation t');
	    return $q;
    }

    public function getMenuTree($primary_key = false)
    {
        $q = $this->createQuery('a')
          ->leftJoin('a.Translation t')
          ->orderBy('a.root_id')
          ->addOrderBy('a.lft')
        ;

        if($primary_key)
        {
            $q->addWhere('a.root_id =?', $primary_key);
            $q->addWhere('a.id !=?', $primary_key);
        }

        return $q->execute(array(),  Doctrine_Core::HYDRATE_ARRAY_HIERARCHY);
    }

}