<?php

/**
 * Artcategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Artcategory extends BaseArtcategory
{
    public function getSubCategoryIds()
    {
    	$q = Doctrine_Query::create()
    		->from('Artcategory c')
            ->where('c.root_id =?', $this->getRootId())
            ->addWhere('c.level >= ?', $this->getLevel())
            ->addWhere('c.lft >= ?', $this->getLft())
        ;

        $array = $q->fetchArray();
        $return = array();
        foreach($array as $one)
        {
        	$return[] = $one['id'];
        }

        return $return;
    }

    public function delete(Doctrine_Connection $conn = null)
    {
        if($this->getRecordKey())
        {
            return false;
        }
        parent::delete();
    }

    public function getPublicArticles()
    {
        $q = Doctrine_Query::create()
            ->from('Article a')
            ->leftJoin('a.Translation t')
            ->where('a.artcategory_id =?', $this->getPrimaryKey())
            ->addWhere('a.is_public =?', true)
            ->orderBy('a.created_at desc');

        return $q->execute();
    }
}
