<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }

    public function getByArtCategory($id)
    {
    	$q = $this->createQuery('a')
    		->leftJoin('a.Translation t')
    		->addWhere('a.artcategory_id =?', $id)
    		->addWhere('a.is_public =?', true);
    	return $q->execute();
    }

    public function getLastByCategory($id)
    {
    	$artcategory = ArtcategoryTable::getInstance()->find($id);
    	$ids = $artcategory->getSubCategoryIds();
    	$q = $this->createQuery('a')
    		->leftJoin('a.Translation t')
    		->WhereIn('a.artcategory_id', $ids)
    		->addWhere('a.is_public =?', true)
    		->orderBy('created_at desc')
    		->limit(1);
    	return $q->fetchOne();
    }
}