<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle
{
	public function delete(Doctrine_Connection $conn = null)
    {
    	if($this->getRecordKey())
    	{
    		return false;
    	}
        parent::delete();
    }

    public function save(Doctrine_Connection $conn = null)
    {
    	DoctrineBugfixesclass::generateSlugOnUpdatedObjectWithI18n($this, $conn, 'title');
		parent::save($conn);
    }

    public function getPictures()
	{
		return $this->getGallery()->getPictures();
	}

	public function getDefaultPicture()
	{
		return $this->getGallery()->getDefaultPicture();
	}

    public function getExcerpt($length = 200)
    {
        $content = $this->getContent();
        return Tools::substrText($content, $length);
    }

}
