<?php

/**
 * File
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class File extends BaseFile
{
	public function delete(	Doctrine_Connection $conn = null)
	{
		@unlink($this->getPath());
		parent::delete();
		return true;
	}

	public function getPath()
	{
		return '/uploads/files/' . $this->getFile();
	}
}
