<?php

/**
 * Gallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ramaform
 * @subpackage model
 * @author     Paweł Sałajczyk <psalajczyk@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Gallery extends BaseGallery
{
	public function getDefaultPicture()
	{
		$q = Doctrine_Query::create()
			->from('Picture')
			->where('gallery_id =?', $this->getPrimaryKey())
			->andWhere('is_default =?', true);
		return $q->fetchOne();
	}

	public function delete(Doctrine_Connection $conn = null)
	{
		if($this->getRecordKey())
    	{
    		return false;
    	}

		$pictures = $this->getPictures();
		foreach($pictures as $picture)
		{
			$picture->delete(null, true);
		}
		//exit;

		parent::delete($con);
	}
}
