<?php

/**
 * GalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gallery');
    }

    public function getFirst()
    {
    	return $this->createQuery('g')
            ->where('show_list =?', true)
    		->orderBy('g.id asc')
    		->fetchOne();
    }

    public function getAllOnList()
    {
        return $this->createQuery('g')
            ->where('show_list =?', true)
            ->execute();
    }
}