<?php

/**
 * SliderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SliderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SliderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Slider');
    }

    public function getOrdered()
    {
    	$q = $this->createQuery()
    		->where('is_public =?', true)
    		->orderBy('position asc');
    	return $q->execute();
    }

    public function getRandom()
    {
        $q = $this->createQuery()
            ->where('is_public =?', true)
            ->orderBy('RAND()');
        return $q->execute();
    }

    public function getOrderedQuery(Doctrine_Query $q)
    {
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Translation t');
        $q->orderBy($rootAlias . '.position asc');
        return $q;
    }
}