generator:
  class: sfDoctrineGenerator
  param:
    model_class:           contact
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contact
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css: nothing

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  
        class: false
      form:    ~
      edit:    
        title: Edytuj dane kontaktowe
      new:     ~
