generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    css: nothing

    config:
      fields:
        password_again: { label: "Hało (ponownie)" }
        password: { label: "Hało" }
        username: { label: "Login" }
        created_at: { label: "Data dodania" }
        last_login: { label: "Ostatnie logowanie" }
        first_name: { label: "Imię" }
        last_name: { label: "Nazwisko" }
        email_address: { label: "E-mail" }
      list:
        title:   Użytkownicy
        display: [=username, created_at, last_login]

      form:
        class: sfGuardUserAdminForm
        display:
          "User":                   [first_name, last_name, email_address, username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, groups_list, permissions_list]

      edit:
        title: Edycja użytkownika "%%username%%"

      new:
        title: Nowy użytkownik

      filter:
        class: false