generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Slider
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          slider
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css: nothing

    config:
      actions: ~
      fields:  
        position: {label: Pozycja}
        is_public: {label: Widoczny?}
      list:    
        table_method: getOrderedQuery
        title: Slider
        display: [=text, is_public]
        object_actions:
          _edit: ~
          up: {label: Do góry}
          down: {label: Na dół}
          _delete: ~
      filter:  
        class: false
      form:    ~
      edit:    
        title: Edytuj slider
      new:     
        title: Nowy slider
